#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude -Iext/include
CFLAGS = -Wall -DCONFIG_CTRL_IFACE -DCONFIG_CTRL_IFACE_UNIX
RESINC = 
LIBDIR = 
LIB = -ludev -lpthread -lstdc++fs -ltinyxml2 -lminiz -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio libutils.a
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DNDEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = ./enea_debug

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = ./enea

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/gui.o $(OBJDIR_DEBUG)/src/menu.o $(OBJDIR_DEBUG)/src/mainstate.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/logwriter.o $(OBJDIR_DEBUG)/src/list.o $(OBJDIR_DEBUG)/src/layer.o $(OBJDIR_DEBUG)/src/langfile.o $(OBJDIR_DEBUG)/src/inputmanager.o $(OBJDIR_DEBUG)/src/node.o $(OBJDIR_DEBUG)/src/generalemulator.o $(OBJDIR_DEBUG)/src/fontmanager.o $(OBJDIR_DEBUG)/src/filesystem.o $(OBJDIR_DEBUG)/src/errorstate.o $(OBJDIR_DEBUG)/src/emulator.o $(OBJDIR_DEBUG)/src/database.o $(OBJDIR_DEBUG)/src/cfgfile.o $(OBJDIR_DEBUG)/src/advmame.o $(OBJDIR_DEBUG)/src/scene.o $(OBJDIR_DEBUG)/src/xmldatabase.o $(OBJDIR_DEBUG)/src/wirelessconnection.o $(OBJDIR_DEBUG)/src/texturemanager.o $(OBJDIR_DEBUG)/src/text.o $(OBJDIR_DEBUG)/src/state.o $(OBJDIR_DEBUG)/src/sprite.o $(OBJDIR_DEBUG)/src/soundmanager.o $(OBJDIR_DEBUG)/src/signaler.o $(OBJDIR_DEBUG)/src/row.o $(OBJDIR_DEBUG)/src/rompart.o $(OBJDIR_DEBUG)/src/rom.o $(OBJDIR_DEBUG)/src/result.o $(OBJDIR_DEBUG)/src/removabledisk.o $(OBJDIR_DEBUG)/src/rectangle.o $(OBJDIR_DEBUG)/src/popup.o $(OBJDIR_DEBUG)/src/observer.o $(OBJDIR_DEBUG)/ext/wpa_ctrl.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/gui.o $(OBJDIR_RELEASE)/src/menu.o $(OBJDIR_RELEASE)/src/mainstate.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/logwriter.o $(OBJDIR_RELEASE)/src/list.o $(OBJDIR_RELEASE)/src/layer.o $(OBJDIR_RELEASE)/src/langfile.o $(OBJDIR_RELEASE)/src/inputmanager.o $(OBJDIR_RELEASE)/src/node.o $(OBJDIR_RELEASE)/src/generalemulator.o $(OBJDIR_RELEASE)/src/fontmanager.o $(OBJDIR_RELEASE)/src/filesystem.o $(OBJDIR_RELEASE)/src/errorstate.o $(OBJDIR_RELEASE)/src/emulator.o $(OBJDIR_RELEASE)/src/database.o $(OBJDIR_RELEASE)/src/cfgfile.o $(OBJDIR_RELEASE)/src/advmame.o $(OBJDIR_RELEASE)/src/scene.o $(OBJDIR_RELEASE)/src/xmldatabase.o $(OBJDIR_RELEASE)/src/wirelessconnection.o $(OBJDIR_RELEASE)/src/texturemanager.o $(OBJDIR_RELEASE)/src/text.o $(OBJDIR_RELEASE)/src/state.o $(OBJDIR_RELEASE)/src/sprite.o $(OBJDIR_RELEASE)/src/soundmanager.o $(OBJDIR_RELEASE)/src/signaler.o $(OBJDIR_RELEASE)/src/row.o $(OBJDIR_RELEASE)/src/rompart.o $(OBJDIR_RELEASE)/src/rom.o $(OBJDIR_RELEASE)/src/result.o $(OBJDIR_RELEASE)/src/removabledisk.o $(OBJDIR_RELEASE)/src/rectangle.o $(OBJDIR_RELEASE)/src/popup.o $(OBJDIR_RELEASE)/src/observer.o $(OBJDIR_RELEASE)/ext/wpa_ctrl.o

all: before_build build_debug build_release after_build

clean: clean_debug clean_release

before_build: 

after_build: 
	cbp2make -in enea.cbp -out Makefile

before_debug: 
	test -d . || mkdir -p .
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/ext || mkdir -p $(OBJDIR_DEBUG)/ext

after_debug: 

build_debug: before_debug out_debug after_debug

debug: before_build build_debug after_build

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/gui.o: src/gui.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gui.cpp -o $(OBJDIR_DEBUG)/src/gui.o

$(OBJDIR_DEBUG)/src/menu.o: src/menu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/menu.cpp -o $(OBJDIR_DEBUG)/src/menu.o

$(OBJDIR_DEBUG)/src/mainstate.o: src/mainstate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/mainstate.cpp -o $(OBJDIR_DEBUG)/src/mainstate.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/logwriter.o: src/logwriter.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/logwriter.cpp -o $(OBJDIR_DEBUG)/src/logwriter.o

$(OBJDIR_DEBUG)/src/list.o: src/list.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/list.cpp -o $(OBJDIR_DEBUG)/src/list.o

$(OBJDIR_DEBUG)/src/layer.o: src/layer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/layer.cpp -o $(OBJDIR_DEBUG)/src/layer.o

$(OBJDIR_DEBUG)/src/langfile.o: src/langfile.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/langfile.cpp -o $(OBJDIR_DEBUG)/src/langfile.o

$(OBJDIR_DEBUG)/src/inputmanager.o: src/inputmanager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/inputmanager.cpp -o $(OBJDIR_DEBUG)/src/inputmanager.o

$(OBJDIR_DEBUG)/src/node.o: src/node.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/node.cpp -o $(OBJDIR_DEBUG)/src/node.o

$(OBJDIR_DEBUG)/src/generalemulator.o: src/generalemulator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/generalemulator.cpp -o $(OBJDIR_DEBUG)/src/generalemulator.o

$(OBJDIR_DEBUG)/src/fontmanager.o: src/fontmanager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fontmanager.cpp -o $(OBJDIR_DEBUG)/src/fontmanager.o

$(OBJDIR_DEBUG)/src/filesystem.o: src/filesystem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/filesystem.cpp -o $(OBJDIR_DEBUG)/src/filesystem.o

$(OBJDIR_DEBUG)/src/errorstate.o: src/errorstate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/errorstate.cpp -o $(OBJDIR_DEBUG)/src/errorstate.o

$(OBJDIR_DEBUG)/src/emulator.o: src/emulator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/emulator.cpp -o $(OBJDIR_DEBUG)/src/emulator.o

$(OBJDIR_DEBUG)/src/database.o: src/database.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/database.cpp -o $(OBJDIR_DEBUG)/src/database.o

$(OBJDIR_DEBUG)/src/cfgfile.o: src/cfgfile.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/cfgfile.cpp -o $(OBJDIR_DEBUG)/src/cfgfile.o

$(OBJDIR_DEBUG)/src/advmame.o: src/advmame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/advmame.cpp -o $(OBJDIR_DEBUG)/src/advmame.o

$(OBJDIR_DEBUG)/src/scene.o: src/scene.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/scene.cpp -o $(OBJDIR_DEBUG)/src/scene.o

$(OBJDIR_DEBUG)/src/xmldatabase.o: src/xmldatabase.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/xmldatabase.cpp -o $(OBJDIR_DEBUG)/src/xmldatabase.o

$(OBJDIR_DEBUG)/src/wirelessconnection.o: src/wirelessconnection.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/wirelessconnection.cpp -o $(OBJDIR_DEBUG)/src/wirelessconnection.o

$(OBJDIR_DEBUG)/src/texturemanager.o: src/texturemanager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/texturemanager.cpp -o $(OBJDIR_DEBUG)/src/texturemanager.o

$(OBJDIR_DEBUG)/src/text.o: src/text.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/text.cpp -o $(OBJDIR_DEBUG)/src/text.o

$(OBJDIR_DEBUG)/src/state.o: src/state.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/state.cpp -o $(OBJDIR_DEBUG)/src/state.o

$(OBJDIR_DEBUG)/src/sprite.o: src/sprite.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/sprite.cpp -o $(OBJDIR_DEBUG)/src/sprite.o

$(OBJDIR_DEBUG)/src/soundmanager.o: src/soundmanager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/soundmanager.cpp -o $(OBJDIR_DEBUG)/src/soundmanager.o

$(OBJDIR_DEBUG)/src/signaler.o: src/signaler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/signaler.cpp -o $(OBJDIR_DEBUG)/src/signaler.o

$(OBJDIR_DEBUG)/src/row.o: src/row.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/row.cpp -o $(OBJDIR_DEBUG)/src/row.o

$(OBJDIR_DEBUG)/src/rompart.o: src/rompart.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/rompart.cpp -o $(OBJDIR_DEBUG)/src/rompart.o

$(OBJDIR_DEBUG)/src/rom.o: src/rom.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/rom.cpp -o $(OBJDIR_DEBUG)/src/rom.o

$(OBJDIR_DEBUG)/src/result.o: src/result.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/result.cpp -o $(OBJDIR_DEBUG)/src/result.o

$(OBJDIR_DEBUG)/src/removabledisk.o: src/removabledisk.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/removabledisk.cpp -o $(OBJDIR_DEBUG)/src/removabledisk.o

$(OBJDIR_DEBUG)/src/rectangle.o: src/rectangle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/rectangle.cpp -o $(OBJDIR_DEBUG)/src/rectangle.o

$(OBJDIR_DEBUG)/src/popup.o: src/popup.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/popup.cpp -o $(OBJDIR_DEBUG)/src/popup.o

$(OBJDIR_DEBUG)/src/observer.o: src/observer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/observer.cpp -o $(OBJDIR_DEBUG)/src/observer.o

$(OBJDIR_DEBUG)/ext/wpa_ctrl.o: ext/wpa_ctrl.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ext/wpa_ctrl.c -o $(OBJDIR_DEBUG)/ext/wpa_ctrl.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf .
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/ext

before_release: 
	test -d . || mkdir -p .
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/ext || mkdir -p $(OBJDIR_RELEASE)/ext

after_release: 

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/gui.o: src/gui.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gui.cpp -o $(OBJDIR_RELEASE)/src/gui.o

$(OBJDIR_RELEASE)/src/menu.o: src/menu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/menu.cpp -o $(OBJDIR_RELEASE)/src/menu.o

$(OBJDIR_RELEASE)/src/mainstate.o: src/mainstate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/mainstate.cpp -o $(OBJDIR_RELEASE)/src/mainstate.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/logwriter.o: src/logwriter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/logwriter.cpp -o $(OBJDIR_RELEASE)/src/logwriter.o

$(OBJDIR_RELEASE)/src/list.o: src/list.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/list.cpp -o $(OBJDIR_RELEASE)/src/list.o

$(OBJDIR_RELEASE)/src/layer.o: src/layer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/layer.cpp -o $(OBJDIR_RELEASE)/src/layer.o

$(OBJDIR_RELEASE)/src/langfile.o: src/langfile.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/langfile.cpp -o $(OBJDIR_RELEASE)/src/langfile.o

$(OBJDIR_RELEASE)/src/inputmanager.o: src/inputmanager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/inputmanager.cpp -o $(OBJDIR_RELEASE)/src/inputmanager.o

$(OBJDIR_RELEASE)/src/node.o: src/node.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/node.cpp -o $(OBJDIR_RELEASE)/src/node.o

$(OBJDIR_RELEASE)/src/generalemulator.o: src/generalemulator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/generalemulator.cpp -o $(OBJDIR_RELEASE)/src/generalemulator.o

$(OBJDIR_RELEASE)/src/fontmanager.o: src/fontmanager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fontmanager.cpp -o $(OBJDIR_RELEASE)/src/fontmanager.o

$(OBJDIR_RELEASE)/src/filesystem.o: src/filesystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/filesystem.cpp -o $(OBJDIR_RELEASE)/src/filesystem.o

$(OBJDIR_RELEASE)/src/errorstate.o: src/errorstate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/errorstate.cpp -o $(OBJDIR_RELEASE)/src/errorstate.o

$(OBJDIR_RELEASE)/src/emulator.o: src/emulator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/emulator.cpp -o $(OBJDIR_RELEASE)/src/emulator.o

$(OBJDIR_RELEASE)/src/database.o: src/database.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/database.cpp -o $(OBJDIR_RELEASE)/src/database.o

$(OBJDIR_RELEASE)/src/cfgfile.o: src/cfgfile.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/cfgfile.cpp -o $(OBJDIR_RELEASE)/src/cfgfile.o

$(OBJDIR_RELEASE)/src/advmame.o: src/advmame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/advmame.cpp -o $(OBJDIR_RELEASE)/src/advmame.o

$(OBJDIR_RELEASE)/src/scene.o: src/scene.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/scene.cpp -o $(OBJDIR_RELEASE)/src/scene.o

$(OBJDIR_RELEASE)/src/xmldatabase.o: src/xmldatabase.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/xmldatabase.cpp -o $(OBJDIR_RELEASE)/src/xmldatabase.o

$(OBJDIR_RELEASE)/src/wirelessconnection.o: src/wirelessconnection.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/wirelessconnection.cpp -o $(OBJDIR_RELEASE)/src/wirelessconnection.o

$(OBJDIR_RELEASE)/src/texturemanager.o: src/texturemanager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/texturemanager.cpp -o $(OBJDIR_RELEASE)/src/texturemanager.o

$(OBJDIR_RELEASE)/src/text.o: src/text.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/text.cpp -o $(OBJDIR_RELEASE)/src/text.o

$(OBJDIR_RELEASE)/src/state.o: src/state.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/state.cpp -o $(OBJDIR_RELEASE)/src/state.o

$(OBJDIR_RELEASE)/src/sprite.o: src/sprite.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/sprite.cpp -o $(OBJDIR_RELEASE)/src/sprite.o

$(OBJDIR_RELEASE)/src/soundmanager.o: src/soundmanager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/soundmanager.cpp -o $(OBJDIR_RELEASE)/src/soundmanager.o

$(OBJDIR_RELEASE)/src/signaler.o: src/signaler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/signaler.cpp -o $(OBJDIR_RELEASE)/src/signaler.o

$(OBJDIR_RELEASE)/src/row.o: src/row.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/row.cpp -o $(OBJDIR_RELEASE)/src/row.o

$(OBJDIR_RELEASE)/src/rompart.o: src/rompart.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/rompart.cpp -o $(OBJDIR_RELEASE)/src/rompart.o

$(OBJDIR_RELEASE)/src/rom.o: src/rom.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/rom.cpp -o $(OBJDIR_RELEASE)/src/rom.o

$(OBJDIR_RELEASE)/src/result.o: src/result.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/result.cpp -o $(OBJDIR_RELEASE)/src/result.o

$(OBJDIR_RELEASE)/src/removabledisk.o: src/removabledisk.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/removabledisk.cpp -o $(OBJDIR_RELEASE)/src/removabledisk.o

$(OBJDIR_RELEASE)/src/rectangle.o: src/rectangle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/rectangle.cpp -o $(OBJDIR_RELEASE)/src/rectangle.o

$(OBJDIR_RELEASE)/src/popup.o: src/popup.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/popup.cpp -o $(OBJDIR_RELEASE)/src/popup.o

$(OBJDIR_RELEASE)/src/observer.o: src/observer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/observer.cpp -o $(OBJDIR_RELEASE)/src/observer.o

$(OBJDIR_RELEASE)/ext/wpa_ctrl.o: ext/wpa_ctrl.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ext/wpa_ctrl.c -o $(OBJDIR_RELEASE)/ext/wpa_ctrl.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf .
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/ext

.PHONY: before_build after_build before_debug after_debug clean_debug before_release after_release clean_release

