#ifndef _XMLDATABASE_HPP_
#define _XMLDATABASE_HPP_

#include <tinyxml2.h>

#include "database.hpp"
#include "result.hpp"
#include "filesystem.hpp"
#include "rompart.hpp"

/*this class abstracts the concet of the xml roms database, as it is shared among a lot of MAME emulators (all of them?). As of now it uses tinyxml2 to access the xml file
commonly generated by the emulators and retrieve all the needed informations, use the various get functions
specifying the rom name to retrieve them. As of now extracting a single information is an intensive operation
a caching mechanism could improve this class a lot*/

class XMLDataBase : public DataBase {
    private:
        //members
        tinyxml2::XMLDocument xml_document; //the xml
        const tinyxml2::XMLElement* root_element; //the root node of the xml file (saved here because it needs easy accessing when scanning the xml

        //functions
        const tinyxml2::XMLElement* findRom(const std::string& theName) const; //this returns the node of the rom specified in the parameter
        const tinyxml2::XMLElement* getElement(const tinyxml2::XMLElement* const theRom, const std::string& theName) const; //this returns a SPECIFIC element for the specified rom
        const tinyxml2::XMLAttribute* getAttribute(const tinyxml2::XMLElement* const theElement, const std::string& theName); //this returns a SPECIFIC attribute for a specified element
        std::string getElementValue(const tinyxml2::XMLElement* const theRom, const std::string& theName) const; //this returns the value of the specified element
        std::string getAttributeValue(const tinyxml2::XMLElement* const theElement, const std::string& theName) const; //this returns the value for a specified attribute
        Result loadFromFileEffectively(const fs::path& thePath); //this loads the file from memory

    public:
        //enum
        enum Error { //a lot of things can go wrong
            LOAD_ERROR = 1,
            CORRUPT_FILE_ERROR,
            INVALID_FILE_ERROR
        };

        //ctor
        XMLDataBase(); //it does almost nothing because everytinh happens in the load function

        //functions
        //a lot of them just retrieve the specified information
        std::string getRomName(const std::string& theRomName) const { return getElementValue(findRom(theRomName), "description"); }
        std::string getRomYear(const std::string& theRomName) const { return getElementValue(findRom(theRomName), "year"); }
        std::string getRomManufacturer(const std::string& theRomName) const { return getElementValue(findRom(theRomName), "manufacturer"); }
        bool isRomSupported(const std::string& theRomName) const { return findRom(theRomName) != nullptr; }
        bool isRomRunnable(const std::string& theRomName) const { return isRomSupported(theRomName) && getAttributeValue(findRom(theRomName), "runnable") != "no"; }
        std::string getRomParent(const std::string& theRomName) const { std::string buffer = getAttributeValue(findRom(theRomName), "cloneof"); return getRomName(buffer); }
        std::string getRomOrigin(const std::string& theRomName) const { return getAttributeValue(findRom(theRomName), "romof"); }
        std::vector<RomPart> getRomParts(const std::string& theRomName) const;

};

#endif // _XMLDATABASE_HPP_
