name: Build
run-name: ${{ github.event.event_name == 'schedule' && 'Nightly build' }}

on:
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: "30 01 * * *"

jobs:
    build:
      strategy:
        matrix:
          arch: [x86_64, aarch64, armv7hf]
      uses: ./.github/workflows/build-workflow.yml
      with:
        architecture: ${{ matrix.arch }}
        build_dependencies: ${{ github.event_name == 'schedule' }}
