name: Manual build

on:
  workflow_dispatch:
    inputs:
      build_dependencies:
        description: 'Build dependencies from scratch'
        required: true
        type: boolean

jobs:
    build:
      strategy:
        matrix:
          arch: [Linux-x86_64, Linux-aarch64, Linux-armv7hf]
      uses: ./.github/workflows/build-workflow.yml
      with:
        architecture: ${{ matrix.arch }}
        build_dependencies: ${{ inputs.build_dependencies }}
        build_author: "Manual Build from Github Actions"
