name: Build enea for aarch64 architecture

on:
  pull_request:
    branches: [ "main" ]

env:
  ENEA_ARCH: aarch64
  ENEA_LINUX_ARCH: arm64

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add aarch64 Ubuntu sources
      uses: ryankurte/action-apt@master
      with:
        arch: $ENEA_LINUX_ARCH

    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Install custom Conan recipes and config
      run: conan config install conan && find ${{github.workspace}}/recipes -name conanfile.py -execdir conan export . \;

    - name: Build and run tests
      run: PKG_CONFIG_PATH="/usr/lib/$ENEA_ARCH-linux-gnu/pkgconfig" conan build -pr:h linux-$ENEA_ARCH-gcc-11.3-release -pr:b linux-x86_64-gcc-11.3-host --build missing -c tools.build:skip_test=true ${{github.workspace}}
