name: Build enea for x86_64 architecture

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Install custom Conan recipes and config
      run: conan config install conan && find ${{github.workspace}}/recipes -name conanfile.py -execdir conan export . \;

    - name: Build and run tests
      run: conan build -pr:h linux-x86_64-gcc-11.3-release -pr:b linux-x86_64-gcc-11.3-host --build missing ${{github.workspace}}
