on:
  workflow_call:
    inputs:
      architecture:
        description: 'The architecture to build for'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate inputs
      run: |
        if [[ "${{ inputs.architecture }}" == "x86_64" ]]; then
          echo "ENEA_ARCH=x86_64" >> $GITHUB_ENV
          echo "ENEA_LINUX_ARCH=x86_64" >> $GITHUB_ENV
          echo "ENEA_PKGCONFIG_ARCH=x86_64-linux-gnu" >> $GITHUB_ENV
          echo "ENEA_SKIP_TESTS=False" >> $GITHUB_ENV
          echo "Valid architecture: ${{ inputs.architecture }}"
        elif [[ "${{ inputs.architecture }}" == "aarch64" ]]; then
          echo "ENEA_ARCH=aarch64" >> $GITHUB_ENV
          echo "ENEA_LINUX_ARCH=arm64" >> $GITHUB_ENV
          echo "ENEA_PKGCONFIG_ARCH=aarch64-linux-gnu" >> $GITHUB_ENV
          echo "ENEA_SKIP_TESTS=True" >> $GITHUB_ENV
          echo "Valid architecture: ${{ inputs.architecture }}"
        elif [[ "${{ inputs.architecture }}" == "armv7hf" ]]; then
          echo "ENEA_ARCH=armv7hf" >> $GITHUB_ENV
          echo "ENEA_LINUX_ARCH=armhf" >> $GITHUB_ENV
          echo "ENEA_PKGCONFIG_ARCH=arm-linux-gnueabihf" >> $GITHUB_ENV
          echo "ENEA_SKIP_TESTS=True" >> $GITHUB_ENV
          echo "Valid architecture: ${{ inputs.architecture }}"
        else
          echo "Invalid architecture ${{ inputs.architecture }}. Choose 'x86_64', 'armv7hf' or 'aarch64'"
          exit 1
        fi

    - name: Add arm Ubuntu sources
      if: ${{ inputs.architecture != 'x86_64' }}
      uses: ryankurte/action-apt@master
      with:
        arch: ${{ env.ENEA_LINUX_ARCH }}

    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Install custom Conan recipes and config
      run: conan config install conan && find ${{github.workspace}}/recipes -name conanfile.py -execdir conan export . \;

    - name: Build and run tests
      run: PKG_CONFIG_PATH="/usr/lib/${{ env.ENEA_PKGCONFIG_ARCH }}/pkgconfig" conan build -pr:h linux-${{ env.ENEA_ARCH }}-gcc-11.3-release -pr:b linux-x86_64-gcc-11.3-host --build missing -c tools.build:skip_test=${{ env.ENEA_SKIP_TESTS }} ${{github.workspace}}
