name: Build enea for x86_64 architecture

on:
  pull_request:
    branches: [ "main" ]

env:
  ENEA_ARCH: x86_64
  ENEA_LINUX_ARCH: x86_64
  ENEA_PKGCONFIG_ARCH: x86_64

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Install custom Conan recipes and config
      run: conan config install conan && find ${{github.workspace}}/recipes -name conanfile.py -execdir conan export . \;

    - name: Build and run tests
      run: conan build -pr:h linux-$ENEA_PKGCONFIG_ARCH-gcc-11.3-release -pr:b linux-x86_64-gcc-11.3-host --build missing ${{github.workspace}}
