name: Build
run-name: >-
  ${{ github.event_name == 'schedule' && 'Nightly build' ||
  (github.event_name == 'pull_request' && format('Pull Request #{0} test build', github.event.number) ||
  (github.event_name == 'push' && 'Deploy build' ||
  ' ')) }}

on:
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: "30 01 * * *"

  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
    build:
      name: Build
      strategy:
        matrix:
          arch: [x86_64, aarch64, armv7hf]
      uses: ./.github/workflows/build-workflow.yml
      with:
        architecture: ${{ matrix.arch }}
        build_dependencies: ${{ github.event_name == 'schedule' }}

    deploy:
      if: ${{ github.event_name == 'push' }}
      needs: build
      permissions:
        contents: write
      runs-on: ubuntu-22.04
      name: Deploy
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

          # (needed due to this issue: https://github.com/actions/checkout/issues/1471)
        - name: Fetch tags
          run: git fetch --prune --unshallow --tags

        - uses: little-core-labs/get-git-tag@v3.0.1
          id: tagName
          name: Get git tag

        - uses: actions/setup-python@v1
          name: Setup Python

        - uses: BSFishy/pip-action@v1
          name: Install commitizen
          with:
            packages: Commitizen

        - name: Get incremental changelog
          run: cz changelog --file-name body.md ${{ steps.tagName.outputs.tag }}

        - name: Create draft release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.tagName.outputs.tag }}
            release_name: ${{ format('Enea {0}', steps.tagName.outputs.tag) }}
            draft: true
            prerelease: false
            body_path: ${{ github.workspace }}/body.md

        - name: Download build result
          uses: actions/download-artifact@v4
          with:
            path: ${{ github.workspace }}/deploy

        - uses: shogo82148/actions-upload-release-asset@v1
          name: Upload files
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ github.workspace }}/deploy/Enea-*/*
