name: Build Nightly
run-name: Nightly Build

on:
  schedule:
    - cron: "30 01 * * *"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        arch: [Linux-x86_64, Linux-aarch64, Linux-armv7hf, Windows]
    uses: ./.github/workflows/build-workflow.yml
    with:
      architecture: ${{ matrix.arch }}
      build_dependencies: true
      embed_update_info: false
      build_author: Nightly Build
